/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedHorariosRouteImport } from './routes/_authenticated/horarios'
import { Route as AuthenticatedRecorrenciaRouteImport } from './routes/_authenticated/recorrencia'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorariosRoute = AuthenticatedHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecorrenciaRoute =
  AuthenticatedRecorrenciaRouteImport.update({
    id: '/recorrencia',
    path: '/recorrencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/recorrencia': typeof AuthenticatedRecorrenciaRoute
  '/servicos': typeof AuthenticatedServicosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/recorrencia': typeof AuthenticatedRecorrenciaRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/horarios': typeof AuthenticatedHorariosRoute
  '/_authenticated/recorrencia': typeof AuthenticatedRecorrenciaRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agentes'
    | '/contas'
    | '/horarios'
    | '/recorrencia'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agentes'
    | '/contas'
    | '/horarios'
    | '/recorrencia'
    | '/servicos'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agentes'
    | '/_authenticated/contas'
    | '/_authenticated/horarios'
    | '/_authenticated/recorrencia'
    | '/_authenticated/servicos'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horarios': {
      id: '/_authenticated/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AuthenticatedHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorrencia': {
      id: '/_authenticated/recorrencia'
      path: '/recorrencia'
      fullPath: '/recorrencia'
      preLoaderRoute: typeof AuthenticatedRecorrenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedHorariosRoute: typeof AuthenticatedHorariosRoute
  AuthenticatedRecorrenciaRoute: typeof AuthenticatedRecorrenciaRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedHorariosRoute: AuthenticatedHorariosRoute,
  AuthenticatedRecorrenciaRoute: AuthenticatedRecorrenciaRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
